name       : font-hack-ttf
version    : '2.020'
release    : 2
source     :
    - https://github.com/chrissimpkins/Hack/releases/download/v2.020/Hack-v2_020-ttf.tar.xz : 529005af0992a41c82cdd77ab9636fc5d1094ec877b40f1d91298a9e290209a4
license    : OFL-1.1
component  : desktop.font
summary    : A typeface designed for source code
description: |
    A typeface designed for source code
install    : |
    fontDir=$installdir/usr/share/fonts/truetype/hack
    install -dm00644 $fontDir
    mv $workdir/*.ttf $fontDir/
