name       : font-hack-ttf
version    : '3.000'
release    : 3
source     :
    - https://github.com/source-foundry/Hack/releases/download/v3.000/Hack-v3.000-ttf.tar.xz : 2237f89b9e0b884f1f72e4804d8cd689f00d521078882df4759cfe354808ba29
license    :
    - MIT
    - Copyright
component  : desktop.font
summary    : A typeface designed for source code
description: |
    A typeface designed for source code
install    : |
    fontDir=$installdir/usr/share/fonts/truetype/hack
    install -dm00644 $fontDir
    mv $workdir/*.ttf $fontDir/
