name       : font-hack-ttf
version    : '3.003'
release    : 4
source     :
    - https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.tar.xz : d9ed5d0a07525c7e7bd587b4364e4bc41021dd668658d09864453d9bb374a78d
license    :
    - MIT
    - Copyright
component  : desktop.font
summary    : A typeface designed for source code
description: |
    A typeface designed for source code
install    : |
    fontDir=$installdir/usr/share/fonts/truetype/hack
    install -dm00644 $fontDir
    mv $workdir/*.ttf $fontDir/
