name       : font-hack-ttf
version    : 2.019
release    : 1
source     :
    - https://github.com/chrissimpkins/Hack/releases/download/v2.019/Hack_v2_019-ttf.tar.xz : 360f9f915f60a9fe66911cde857d46594325216568e58c25cfb672673b0673cc
license    : OFL-1.1
summary    : A typeface designed for source code
description: |
    A typeface designed for source code
install    : |
    fontDir=$installdir/usr/share/fonts/truetype/hack
    install -dm755 $fontDir
    mv $srcdir/*.ttf $fontDir/
